const frontenders = [
    'Bjarni Olsen',
    'Bjørn Barfoed',
    'Casper Andersen',
    'Christian Broström',
    'Christine Nielsen',
    'Christopher Bourlon',
    'Dan Sørensen',
    'Dennis Haulund',
    'Eduardo Verillo',
    'Elise Bach',
    'Jeppe Skovsen',
    'Jimmi Nielsen',
    'Johnny Kritensen',
    'Jonas Kristensen',
    'Leo Karsbæk',
    'Mads Hornbæk',
    'Mariann Madsen',
    'Marlene Thorlund',
    'Michael Laudridsen',
    'Michelle Engholm',
    'Mona Thomsen',
    'Nicolai Nielsen',
    'Pernille Kloth',
    'Peter Krogh',
    'Sune Popp',
    'Søren Husted',
];

export default frontenders;